DROP DATABASE team4;
CREATE DATABASE team4;
use team4;

CREATE TABLE PATIENTINFO(
patient_id BIGINT NOT NULL,
sex VARCHAR(10),
age VARCHAR(10),
country VARCHAR(50),
province VARCHAR(50),
city VARCHAR(50),
infection_case VARCHAR(50),
infected_by BIGINT,
contact_number INT,
symptom_onset_date DATE,
confirmed_date DATE,
released_date DATE,
decreased_date DATE,
state VARCHAR(20),
Hospital_id INT,
PRIMARY KEY(patient_id)
);

CREATE TABLE CASEINFO(
case_id INT NOT NULL,
province VARCHAR(50),
city VARCHAR(50),
infection_group TINYINT(1),
infection_case VARCHAR(50),
confirmed INT,
latitude float,
longitude float,
PRIMARY KEY(case_id)
);

CREATE TABLE REGION(
region_code INT NOT NULL,
province VARCHAR(50),
city VARCHAR(50),
latitude FLOAT,
longitude FLOAT,
elementary_school_count INT,
kindergarten_count INT,
university_count INT,
academy_ratio FLOAT,
elderly_population_ratio FLOAT,
elderly_alone_ratio FLOAT,
nursing_home_count INT,
PRIMARY KEY(region_code)
);

CREATE TABLE WEATHER(
region_code INT NOT NULL,
province VARCHAR(50),
wdate DATE NOT NULL,
avg_temp FLOAT,
min_temp FLOAT,
max_temp FLOAT,
PRIMARY KEY(region_code, wdate)
);

CREATE TABLE TIMEINFO(
date DATE NOT NULL,
test INT,
negative INT,
confirmed INT,
released INT,
decreased INT,
PRIMARY KEY(date)
);

CREATE TABLE TIMEAGE(
date DATE,
age VARCHAR(10),
confirmed INT,
decreased INT,
PRIMARY KEY(date,age)
);

CREATE TABLE TIMEGENDER(
date DATE,
sex VARCHAR(10),
confirmed INT,
decreased INT,
PRIMARY KEY(date,sex)
);

CREATE TABLE TIMEPROVINCE(
date DATE,
province VARCHAR(50),
confirmed INT,
released INT,
decreased INT,
PRIMARY KEY(date,province)
);

ALTER TABLE PATIENTINFO ADD FOREIGN KEY (infection_case) REFERENCES CASEINFO (infection_case) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (province) REFERENCES REGION (province) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (confirmed_date) REFERENCES WEATHER (wdate) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE PATIENTINFO ADD FOREIGN KEY (confirmed_date) REFERENCES TIMEINFO(date) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (released_date) REFERENCES TIMEINFO (date) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (decreased_date) REFERENCES TIMEINFO (date) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE TIMEAGE ADD FOREIGN KEY (date) REFERENCES TIMEINFO (date) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE TIMEGENDER ADD FOREIGN KEY (date) REFERENCES TIMEINFO (date) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE TIMEPROVINCE ADD FOREIGN KEY (date) REFERENCES TIMEINFO (date) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE PATIENTINFO ADD FOREIGN KEY (age) REFERENCES TIMEINFO (age) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (sex) REFERENCES TIMEGENDER (sex) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE PATIENTINFO ADD FOREIGN KEY (province) REFERENCES TIMEPROVINCE (province) ON DELETE SET NULL ON UPDATE CASCADE;